language: rust
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libssl-dev

cache: cargo
rust:
  - stable
  - beta
  - nightly

script:
  - cargo clean
  - cargo build
  - cargo test --verbose

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin -f
  fi

before_deploy:
  - cargo doc --no-deps

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: target/doc
  on:
    branch: master
    rust: nightly

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    # Uncomment the following line for coveralls.io
    # cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

    # Uncomment the following two lines create and upload a report for codecov.io
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
