[package]
name = "str_utils"
version = "0.3.1-alpha.0"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]
edition = "2021"
publish = false

[dependencies]
unidecode = "0.3"

[build-dependencies]
unicode-normalization = "0.1"
