[package]
name = "str_utils"
version = "0.2.1"
authors = ["Dany Laporte <dany_laporte@hotmail.com>"]
edition = "2018"
publish = false

[dependencies]
static_init = "1"
unidecode = "0.3"
unicode-normalization = "0.1"
